// <auto-generated />
using dal_postgres;
using dto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace dal_postgres.Migrations
{
    [DbContext(typeof(MoneyboardPostgresContext))]
    [Migration("20171107104901_Initialisation")]
    partial class Initialisation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("dal.models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Balance");

                    b.Property<int>("Currency");

                    b.Property<decimal>("InitialBalance");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("dal.models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("dal.models.ImportPayeeSelection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<int>("ImportRegexId");

                    b.Property<string>("ImportedCaption")
                        .IsRequired();

                    b.Property<int>("PayeeId");

                    b.Property<string>("TransactionCaption");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImportRegexId");

                    b.HasIndex("PayeeId");

                    b.ToTable("ImportPayeeSelections");
                });

            modelBuilder.Entity("dal.models.ImportRegex", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RegexString")
                        .IsRequired();

                    b.Property<int>("TransactionType");

                    b.HasKey("ID");

                    b.ToTable("ImportRegexes");
                });

            modelBuilder.Entity("dal.models.Payee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Payees");
                });

            modelBuilder.Entity("dal.models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<decimal>("Amount");

                    b.Property<string>("Caption");

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<string>("ImportedTransactionCaption");

                    b.Property<string>("ImportedTransactionHash");

                    b.Property<int?>("PayeeId");

                    b.Property<int>("Type");

                    b.Property<DateTime?>("UserDate");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PayeeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("dal.models.ImportPayeeSelection", b =>
                {
                    b.HasOne("dal.models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("dal.models.ImportRegex", "ImportRegex")
                        .WithMany("ImportPayeeSelections")
                        .HasForeignKey("ImportRegexId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("dal.models.Payee", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("dal.models.Transaction", b =>
                {
                    b.HasOne("dal.models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("dal.models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("dal.models.Payee", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
